apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: descraibe-db-app-user
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: database
spec:
  encryptedData:
    username: AgCRJmOecQFNZyBsJgq48lRoHIHDrSzftOaJbACVwrirZFdqE+Q41jA1kCCGJoAPQt8xQhQZOdAFRJV1F8dehu9gATe5C7pGaCsH8zC2vSrdB8JAL9eFj5CvhGa+5EjfjtG7P0Tgy9Cb2Z9/GzfsyU20hnfs11psYE/CAW/lORtonAymIc+PlHq+0oGAd6eM96I8+DVWO4JCWtPro6ousa+uesHnEsfmwuymD0LctEIGyeiL4TNcBWKpcxLlQgakroZLGPVdkvYIyxqmxKQ/Qg39RP102NbpS/rTjVi2HJ0bnTYkhVclrwf2vFSaWbN7uVEJ6WjEldJPLBrjb5k27ie5D1ZL1gCTtd1QbouIii8gXhA+efyQl4Tl+ITcUUtxTQbl+rRFsiHILlzooLTqcMrKVuGrNc0z0DzfCLhARxKsqUGSU1vOfTdbg8/DR5I1Xd+KiOdVOH8KrzxhBUVK5UxMukiNIHMKgsrdc6eAcbB7wwCTLhoqfF4hbWqEfmIA5jcpHUQXnLXMdrxP9S6acv/6N4BsvaDQiwajttPpG7+/1PdMIiQZDx8RRyI+z67ER3d6zHhnl9A/OqghoQ3nA/orHpiQ3Q5vjp2KFeb5rP2fD3OuHUkjh2zeDmxB7yEaIaldR+6w77JwPA1dzuyBqDpUySu6UUeBGPh4lNKksNBBPxepI5BWW0RavBLKFYAhXSE64aeY2ZTNxqZ+gpqb
    password: AgAo47HFeERi+fi8lxIS0AorDLx2R+W2C5BzWle7tHYg5TiC089sULcdag8Aiut9rImmghiiK8UjcJDFoMCOxS81i/zg+OaaB4O/jVn8LvcPotjbbJCNSVM7f13YM/1VqNoE+CbLGtZRQbjeU16o/VIhSJPy7nWc5lp2REZhsynuxMuMI/EjPAFPImMQlCLILLvm364rTSuxgEnIxTUbu/YSXTDcdBMsKEgV1OqGSKSgyO82a3YVAfhOTMJpbzOZ3hrbWEVPaLbt1/9IgpRPfhCjSo72LA26cuAM6yEVcGHhBz6funt0dBmVVq71EHG00BiTLRlA2xAwR8m14z1WrKClq6mC4n5uBaJyG+TXj+amAeXfZRt7A61pgRtoCfGoi5pemjImQz4rTgETt17mpvEddxTy3v8WAkobtnLcZk2l1oFXNPogda2Jwm5ZB3TjWe3SDDw3hj71qM9l5TfjAe2reDcLwuPb+K2xbZrK6mrMoDC9GcJYozmItMjScaXToab3MMWQ8scLgznt+8Sf+DSY/YHOQ1X3mzmT45BO/LH+QLBFlY5p0uMoQt4PoNoLLHnESWALSypThoTXPDUOI9fIUVndWh8zyjOfgLVrj3G6hiaqBzrRMnihKcSLBLg0B03Ioe0ZGYqurX+ubTzQOjJlyyjC0DworEnArzMwR7PWR5CzU9WOf5up6fhoH7sKwHx0UEWhWRMpSFSKrhEGbfuZAYw085nESQHZ82QfE4NfvlXyQg3T/W62pkxmajcZCjE=
  template:
    metadata:
      name: descraibe-db-app-user
      namespace: audiodeskription
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: descraibe-db-superuser
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: database
spec:
  encryptedData:
    username: AgCp1+SlAJWrgyg0f/fIO+3uvvQQOc0L4/G2y/ZkO7C2zI0Orxr3wr/5k/4ozoo2cqrMGr3In9Qo2A0LAME51bv0XAO45mqHTyJA1EIuNhTTDExio10psTG0Dhl3iahqjA+OjTBOV5rkcjJesK5by4cTzWbBIQ0gwtjykVrygH5V5suHSiLPbo7LAjk6yZCYIGAI2rmceKTLmQgm5upT5w/ByRKJtw5awpS7CpcWysiV9YHmuU5X65TG3RyTVR86ihfDU8++dkuZjXpHop+4DVWQXMwlVIJBBqH1RfFM9F/fchT92YYswtrKY/+wz30JkO6k/A/HCHH8aD42IVOhKUt7f/Dg91B1WRMJ3KSye/cZ0qC4nnWEu7WUR9X/pjJ8rj67pnV9ostMd1pYhXCkqAn2nasx+1FmUnmLJEYHFXzV2xjS0vKVVku2ZoCid3JJxB9+ZCBf6O7v9OuUlFxiX36ZzcAqQgssx9XshcLzHbd1cVpguBZ0TaHSNCJSaMG7rTZwMr/XriQJXUkrGmna/5r1VH9bQglJWe8uJ0kEd0evpkUuB0bXWV+XTO84+3GrkwB5iywtnHigF4r0ubsut9APz3Xef9FPO7McIAAUjfVI9Py7b7wxdg2UOoTyckiuzOtiRQ94pSk9Ag6CX4lW8Rt/9lHrQCi0sGqD2rff42ZnzSTic7SMk7JU4vdPGLel450+3MmN+1znCw==
    password: AgBAyb3EFEBN8dIST8KRiJ2xCNhptsJzD2h1O+xMcIVuGvJhWbnwLNGFx3jWXqf3cOpkTUHZmdaZtLlZ1GFWtnwDFbRaZc3PkO+lJOqkgS2zfcOSh/ppgIImoiSx6JPTQ7zBVJyfiU/xGNLtSZdfiG/W6AmHnm+exVz4ULdaxoVTTi1ATMxvf6koDkf3R5/oJLdAirt1BJaSfSLG4Po/pi06m5WocDf0BdIAHXGuaq4gGXTjczIUIOzxItigPlQ+Z9jhn5jBeCsRiZSxgJKmlcPdExncmV23rnKhO/Xad2OD9nEX43JqCmvzi7u9ptfZlfcH+j0lNyLlrbLybduS+n6lD3yUuJMMtzydGecpWyUjFnKHdFH0Utoxu5X3i6g5e0Rzo0Jye9rNhRBAuLdhqewcxLjAo83a178ibv4etNoLrXhHaRmkuSYkK517a6Hy/OUr8Fs/JCnk9Mx5eqRH0mBu97FYWEuwqm+6QAZAE1cB7jmMo3nKQoE3pDfWAaoa2dFsxFEbGT86jH5pUr8GCxvC/Yg/GsDq64PVeA10LLrTU/iK10/9yQYF8pdePxKJZgW9BjUo86Z5zA12ioR0sdrrVBShdQVq3Ev18zSceMLt0tB/UwnphZsb27agyDF7bbi0WWxeboKzDCDv0MI2ukJyNpNiHjFmegeKolHlWMLprk/eZtrhd3HcaT8K3v0sKMsUpLLBkczbbp01BrCg57NZJC2alGBvI5FRExNbQvNYsPfLrBD/DkWVNIOjivQbTfo=
  template:
    metadata:
      name: descraibe-db-superuser
      namespace: audiodeskription
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: database
    type: kubernetes.io/basic-auth
