apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: audiodeskription

resources:
  - ../../base
  - openai-sealedsecret.yaml
  - cnpg-sealedsecret.yaml

# Updated by release-please for versioned release deployments.
images:
  - name: ghcr.io/fhswf/descraibe/audiodeskription-backend
    newTag: v0.22.3 # x-release-please-version
  - name: ghcr.io/fhswf/descraibe/audiodeskription-frontend
    newTag: v0.22.3 # x-release-please-version
