apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-secret
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: credentials
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgBSs8PxoMxFmHHxrnDVKIArz3msY+FxKjyswOApH7MD9RXzLSZC6TH5vEKoHkY8BhtFYEXY8T3GhogL4A6GId7R0YXAix/lcXb92mo/ELciW0kmXUruDbmVxr8URqSUCIjfurJpKSxc4z5jtW1YxW7+R9YlWkz8mrJuR4CTHALSixdAnd3/ZdmheEVYdU86I7q9uPSM5Jvy9Yr4QNALcgLGOK0RkIaE1Gs71V53ftAv74hYHcknZAM5Ve4h5C/B0sFdf+qWcQg1qj34YX00EfLuSd0QktOf1TMZKuHWt3DBgFAnXaKVj/8up0OLgXSyNdhVelH7nzApoaiZ1TaKc9Yk05pvOWTIIeaUccvFUDrPpy9eZrvG1Z1zzT3R6qUW6ELeaMLuaqUZVXD9kM4xv9uTHvxZBzoZTeHNaHnMmQbrdcr5/tGIQdkkwrZzperj8jQK4YWeRDh69O0nuHLwuKEGF7VZ+G4JXiYaoNL6MnFtjXZ9SVOE8FLiCN847SAJoQKGPDy75RntQPVDfnvjfloQZGzWHrTHLmisr8BeXh9b1UP5ltnJOapmCurzUmVIQ0nc2E1M/Is9bMjBklTDjM8lfGI2ckR0DjjlVgcyA+CieeoQSlVOE9j+Acr5Ae3WUdzFWIqECl5bw5RxxagDYmSmcUgun5Ip4QbfD66GeA36w17gt2olc06WdmSy07PwCZ94UTAsThH4KHqoWt0Ov/+t7ajhSl0AI916leKCY+tesQ==
    OIDC_SESSION_SECRET: AgBtTSZu1ahbAQARYrkrrBWkmdNS9gY88vXuN2veaVrB9Bre7bJieWOervV+hwf3nNpMbTY+e0P3y58Gv/FTpB+kBNBKG0qFv81PG/NwFnA1VVvL6IH+9iQ4uXl74mMfiu8smVz9TPc5cbGL7CHEbWYKyGqPX/otlnRVk8lJ4ufsalBlmPAUyEIRMtr+JvQ9VJliHRh2mQ979Uo+Jca3yEl1sb24fnZVqYRnlixgAgXIYB34anRc24AIfDLMi8f/8YshgBXkCZGhz5+E8q68bEB6KDqILNtDLo5V+UwGxHTZHWjwQAffIErR02Y/gw8u7eJ3qeEiXOnvbfSsmhyaOtFKiFESRskVtfdwPn/aS0HxolNnBx7JrpZnNjv0wr0AipSiTK8f82aAUpA7+RzWL3fIikJJt2ITaiVgX4QEZKNjs3P8Dpi3TlBzUNVSX/9XMhiGv1c0MnX1yAnNYNhMtk9VPcbQ3sRX1uGoY9VwTq762cm/NxIG2J7gih93+TXJiSrCzTIxgj+lrXTcJQpXChFMlgy50EHxj/GAXxYvmCDT/mUdnODKiX3eNGgvLAuFwIOnteJugidPpt6nLR0+AQdPMSolIVP7SGr6iag4X/Q4Xi/HBELCcPj2CRVqKQ6ebr24HPYnPP2wZbVUm25N1v0T5Ycc5UsJaldI2qFTB5k7WfbtoA2yMOidvMNomlVy8aQnZDtObvXzLfXDtQYGfKJEPHVwFfEN3ihemVKnSuMtCCPm7qLqYpreToAficOCt07UdFoA6t393MtOibuYavs=
  template:
    metadata:
      name: oidc-secret
      namespace: audiodeskription
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: credentials
    type: Opaque
