apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-secret
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: credentials
spec:
  encryptedData:
    OPENAI_API_KEY: AgDIepEmbI41G1a4UWpqHiYB0q7D08fyxjXjbfGBEo9BuiNn
8HpiZgLhJeSGUO53jSAjgHF0x528cWMuiDBCM9UOR91NKf8y82hQb4df1v2fx1BNJIA5LlBxapzoSJt6SLXV95wxwFhhE2s7Xwr7udNFpG8snM9WiP9RoOH8yhgYa5km+lqTv8A5yxCjjn6Ny7uxDPrrZ77R37QnHbU0bCccpJyeXQBBfNtXAfD7K5WjorDUprWZ5efoSafBHxDwjo5jCCWfvASIVJUBTzV7LhkY47254zDKG2ZSYecK/HeI6HZ+qAjCASWv6LM63965vKhTg3unSHthsYr8WSHjjydb+xQp5pfc/7gSIydAJnKvl3vhibq8TmKFFjAHaVfibdSG6V7YzOLlG4KkLRLbcidWJLlQNvxaM6NqrRh+Mgb5fojigv5/Hn6302MJkhytGrNDqaYKoUEchSq8EFW6gbfcpWg4rVUU949iBkP7z09HpvzkK4cg8JqnCwzkLrO6aDALz/Mr+FWtw7e1B1+/IvK8MVKkOqM2QqlpR/jyeAZR6cYS+xh61xog75+nokBvpw4vVZ8o7JY3q9Ul28HeXUmBz6hCH8VcbExXlSzo9kdtjYDlhNM56g4PnEJVupC/mcdiWtQSyLQTzzQHaJHgcttdZh7U0X/shsQbSsmGHu+ZdZRhJg10Uhlg7maq+8XZggguAw7oduzPav19Ebu83AVQmnZ3/pH30eBT
    OPENAI_BASE_URL: AgDKeoB0fF0r/MM10H24PgXdeuKuPXva+mpl9BHb4L8qDt/2C4KMu6YEM5nRFSdrHV8gKiou7NvmaC3Mh7ugV8GAMi8qbkJ9z6Zjt9iTB8VqOS8a4au5gUCzdnmrZJcMJ9ocrNpRh3GUWMPypcHZRS12a3aAz6/veBMQGK60oWMVBnrlgjzSpKdR21Z11WrkYLYZ1B8NM024W6cG0+igXagv5TH/AhVJqwp107OkfcCDF9k3zLwPft/fPKBvYe8rRt0FSDU5st2+PBLUR+mLuicZmEaiWhOTgOhnmAuX+2fnMsyo88fMCnRWCtO2XCbfzDvsuuOMmSpPpw5WuDQddfv8WLz3wefMiP9f8DZEwtKzaS7vqH45qa4/aFIFZQDlpvpih490da0HpHteYA8f14rGBpZJm+ZCYj7ZIFH7h3Pg51kgli3XiC91kYdkb0cECyZspifOzOu2opihRSO43ZVZEvxURIW8QZqv8VpxfrEPsNNLmNEoY4pwrKGJzSpW+nEDLiqAiXULRH9xkETOh6EpVeALGht05BzzyaNNgDqfEiXiNYW9zOj1KW9mIdBrJYCEW2OrOpyHa5xHRAQCvnI5GKi8tykUUsse/Von0iiVvJtHdok/ihDZyMqi9BKHIERVFyoWLaDrJqUIuWKk/R+8mX/5jlQK/SglYtLaQ9QdkOXlqRa016+STl1ZRmxG600ovz0bT16JL5i5n1nQCG/P3NegFj5eBuLTuMU=
  template:
    metadata:
      name: openai-secret
      namespace: audiodeskription
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: credentials
    type: Opaque
