apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-secret
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: credentials
spec:
  encryptedData:
    # Replace with a value sealed for:
    #   name: openai-secret
    #   namespace: audiodeskription
    OPENAI_API_KEY: AgBKFJTELZ0+NXJkSf2crIpvunZPO4WMZPJilr4UeNcimVjSXqS05SX38aBsWmiV2PMBedTkCAbwyuXsEvRPjbOOOlbelC2db9CszeVONZWqZwrIKKMQCScmnWGoH3HeEwjCwiUd7zLXUwurczP66ODVm+2hwVVGENkh6XFOQfKlJsaY//b2i5mCWdf2hgDobczQ/FKN09j55+WRo714P0nMnQiCLqSiojpo7uSmLPVmxqC6jFYt4rIKe2qwvQm7ua33rCZy8TorTlj19xkcxTVE7tcC6bEHu8uoK0CCYts1+R9hUTJlWyRlHp4pP9d04yzvAcADOTFFKyhIGEthWux6pHeBBeQKkz+MO/ucWEw0UO8EKKwpGe9Gep7GlwiPjz824FlEU/R7uqccBLfOg5g59k+goLwoWK+Dv63UMxxw8nf6cLDeRK3f7rQXxS/5X6QQyTxFiwYDxOKgd0vKGE0F+2eD3JCCvP0P7J8vH2Mykt8XuaQQ/vLsfGi0zFC+pu8g+eRF/2FIh3u92zQ6NckXfK8qOtzmZBQ0xkbSQjp+3cLKNGLgJ1j/TTFcQ7vHIdCaRW/JL7moUeJ5OxnzKF/jtC47uL8lzWCab7x/oB777ykXNEEHhQnx4iy4SwyUhenL0sGsKwhIN+f0QB12YinneYOnpvsoZA/1jIM2DdiFnSMgBSQMzhsvcTy76WYLRR2ZUJP0vZ1rie4v+k+dgtCTwcRpQsvvunvxo1KhMzJU9YDxv9ileTx57mwMH5EEDzUWDlA85L12Zr+a7JJqaht2/Fvxwxc3aC7fgmJuQuKp1ItO7WKvPMHkB7JF4d8kkv2MMURY3jk7I49B/ut+xAyzE15U5rPSIe7gKP32Z/TezmlRDu0EEUUpxrDKqPQAAeUcnEtY+yMeYvcvmjzGVfYDjRchWAg=
  template:
    metadata:
      name: openai-secret
      namespace: audiodeskription
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: credentials
    type: Opaque
