# backend/pipeline/persons/config.py

# RF-DETR
PERSON_CLASS_ID = 1
RFDETR_CONFIDENCE_THRESHOLD = 0.50

# ByteTrack
LOST_TRACK_BUFFER = 30
TRACK_ACTIVATION_THRESHOLD = 0.70
MINIMUM_CONSECUTIVE_FRAMES = 2
MINIMUM_IOU_THRESHOLD = 0.10
HIGH_CONF_DET_THRESHOLD = 0.60

# Tracking sampling; RetinaFace runs on every second sampled frame.
TRACKING_INTERVAL_SECONDS = 0.233

# RetinaFace
RETINAFACE_CONFIDENCE_THRESHOLD = 0.50
RETINAFACE_NMS_THRESHOLD = 0.40
RETINAFACE_INPUT_SIZE = (640, 640)
RETINAFACE_DYNAMIC_SIZE = False
RETINAFACE_PRE_NMS_TOPK = 5000
RETINAFACE_POST_NMS_TOPK = 750
RETINAFACE_MAX_NUM = 0

FACE_MARGIN_RATIO = 0.10
FACE_ALIGNMENT_SIZE = 112

# Face quality
FACE_QUALITY_IMAGE_SIZE = (112, 112)
FACE_BLUR_THRESHOLD = 5.0