apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiodeskription
  namespace: argocd
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: app-of-apps
spec:
  project: default

  source:
    repoURL: git@github.com:fhswf/Audiodeskriptionen_SS25.git
    targetRevision: main
    path: webapp/k8s/argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
