apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiodeskription-staging
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
    link.argocd.argoproj.io/external-link: "https://descraibe.fh-swf.cloud"
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: audiodeskription
    environment: staging
spec:
  project: default

  source:
    repoURL: git@github.com:fhswf/descraibe.git
    targetRevision: main
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: audiodeskription-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
