apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: audiodeskription

resources:
  - namespace.yaml
  - pvc.yaml
  - cnpg-cluster.yaml
  - cnpg-pooler.yaml
  - configmap-gpt.yaml
  - configmap-prompts.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - ingress.yaml
