apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  # Kustomize adds the staging suffix to resource names.
  name: descraibe-db-app-user
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: database
spec:
  encryptedData:
    username: AgA1N/0PrgULii5KZHZPYlEAo5145yTKXqYewVMYiA4goWRdUxuk2gSq2FKQ6+3SekUTphbdqsB8eNFVFGwFjisf7+jsvY9yob5RiNuHU7GFFma2HedsSQZ8hpQBmVim/w9r/n5kq86UG6vCU4Ju/kZUYrosNC13+wbbh51C8m29IQroNpgLr39q++J5N5tDHOgp/PurvnT7rSq9zFtgpr8MjxGcGvY3M6QDn913xROg7b0zpQBfLJr6X0PqpOUaI7rqs5Uoi4y5qRrz+Vtr1O+JbyI6kOKOmuIhoGth8p2Nz/qIwvz0yC25o1n0ZxLGpMzWS/iqkBYsVAqNJWJQnPbzl4mRns0HQylHJUGoxAh4P/IQxCzfUZw8aDr48N/Fk7YrzblAdlEty7LOVCvLv8hl6fEJrmJR1k6eZiIYxU8qGun0qg66b1KV6WLSYo/eLcHZ+JwGvcm50uiaK7tsLtbjMiTgMRuzdfowkeowdTLvEBIiez/yzBLljuYy4kGJ+H/pdhiO0h3HJDieRxUFAcUkejvLjannwIAAXU1XJ7hFxVCVOU7QvYmWDx5p+IRCskCNBztRaVZiiy4G2x8VC7D6csqCIh2/tcgOLUhUIY2Lq09o8VRhMLDfqX/ZXZPcRUa2BjKbWPd0cadPYELQzwr4rz8NpghqrK42NoPc4wTgTdFwRH+67G8E24BwYLxuXLt7ZEpZi+bkX/J2gjLy
    password: AgBUUJD69f0c1biNBUZkhNk5N+aGsfUd/IM8DrOOjPLOJKwsIurInEEyx4YxKFb0pVE6DxTmo7vS5y/GDHAZJm4Sf6D1+xgQ+appnQF6Bx7L4u4sq0UJitMdcr5QPmA2VEpukfQYeEYpOOmeSt1RIRtJdn3M3vASu88kzqf+/7F4DKQePcbjj8SKTcGHlY6WYXqVLwXw3fYG8lko8Oci2ymCA9BI/5fXUugFv6Qsp8N7razVeC4dLiQg8ayW92skhcv3hcLTzIyTjM98N/Aor870RLnTm2PnNAGJjZ5CpowDsSf32yAwDFFDxO3cjsoUqWtUDvpiY1YggJPd9hkWZpfj+wGYKRaGz4iafOWw1iKMMYT0AWOrf4eSliblJR7Xe00aJ/MD91MzxS+VIKwZsOKEIpzs9cikF/a2ziICd1uE3AOIeybUbTh7H33I6piPuUp2d2NOw/lepNFfeLNRrAaLpf/OhNaablytbYOBadbcfPVEzs4uqIs3D2JAFHNm7h8muM+UZYRJCp2q9l7R+sFkY0vgVeS3wT1TrZCdqPNvHBJ5TjwdQ5FVYGEOBGgF32hN1ar7fNmqw2UmByeApHgKQ9y/eKLedrpCxq3FJgZLkCDvwDfpxsKTubhP9hj0qeScjDdOvkhVBSStcu/ljxEc72Sel67TbAtEw+arZqDEWZcAQ5JK6nuLXJzvJ/iOQA8EODrRqzm97kF6q5uAiU6K7E6GqaTqV6syd40Es/ASJjXpfv+GJ3xbYsDOL9qlc6s=
  template:
    metadata:
      # Keep explicit final secret name to match patched Cluster spec.
      name: descraibe-db-app-user-staging
      namespace: audiodeskription-staging
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: descraibe-db-superuser
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: database
spec:
  encryptedData:
    username: AgAPQy/YY7zBTMfKq+tpCco69bcLlHQa+xOT7szlvZj5Bdwg/yvJI86QFnkwLVZFuo7ZY+hlLOGPGnVwgJ29h1DVIjrzScIquAmrFKQ3oPTyquW64qTTTn3GoMwkJRH3H/MgZ9LrsG5R3EeJJJeX3pLSVR2baYUEG/kZRXW1alV2PKjRRaWFiavFnb4enQqRbGcMffGhNF+zkuptEaddDk0g9Jaa1U4O2DIE3sva2st5xf9B99X6ROLqhr6sBvSx8MfRvhFVroEL0mxlDVYckZNEwIhUtVyXfreUgxfwCeM+pArrICGUdzuRzGt/UjK3O4BYX72UoOJKnrG8UNqgQo1FSuf0mYtxXpbg969pn12gGHlHHTm3N8pCmkH0il6aAlgbat/X8JQ+U5iEWtLf27koIIhU8Crp5n2rywVRWG/ooKsUirCLu8ms8bRhW8g5S/jxQA+RuPyKR2HrpCwiqbzWyeFKhWY+Gpf8Uh55GjNseLGE818xavXpxpaOaJazaiKlJcW0pfSDlaPt8RD+xJpaD1x1qnOaa0uA2WxPMQfkkhxWDB7TAldFBSVwmkzKZ0nXqmg10A1pTRT9g1o+plgMKc5xGT5aK/NeOYeTyUJoJMktK22HCjliNT80z7BTKB4z7ZVo2+1OsXYqt7d0ytKff5iqJ+zLc0yoahn90Z6P8mzplJgmMNajd6AZf0oSFJWm79VXSk59HA==
    password: AgAYD09b6q5RkHiOYFcFIJ98aYTbakoPhCLq9NReE5Lgw54UmWfdTTxF7DYOWh6b7M7ad58jJ+165omglB6BDtYLXSR8ZHYvx5gXHFVnZhByfu51hoYzmYBILXlNkET/t1yh3truYbpUyTqeb/necwNnjgrNE9hN8gHlH4/MViKR+m82NDez/zGBwitfxj0DCrMkzf+NwKvKWt23+KeVq9Hsn82g3jqQAzVDscBK0TetdpKaA+fWYPGGquLcBuWTB4rg+FlCtovX7spJgIVkQvRMMWr/YpDR6F9cOoOal09TmXwW4e/tS9uJFRHogh3+XuxGTPU9SQnmdjL1fK+zoa5YFf0RaqzFX3EoueoxR8dn9OJp6fhUK5o/BbTmYoY5tqbWi6D9J0bQelRATlHbe4L8ffbF5U4FIiP/AhvxLEcBa6+sTB3fnmQ5NSeyPmd5vmL1qHabjc6qQ3ZflcfmnE1Oc7W6xTbSI8oO4YYGpjNcRlU4cuYpZ/hHBTabZXe1PX6MejkNyTmevWg2GjBKHc4V2o+2/ew4VxU7wI+4QM3zKj7p5adlufaH/gribElHcuVUhevrC+gTdCUL/2PskIrMXdNoUzm6zDvI6IVrcNIZ/bUebBUiV/dP4SyBd+VTdUIA3oN1E9yzdNAYgLzkbxbOLD5pjxgqGfwX/sX8CSo8qGujMQvxIFbmbdiquaz6CQZK8GrzOfk7/IkuYJmQik1M6x71yv2nOMZYtad1ttUzaP4i+gWiTeW2w9NINWzocYY=
  template:
    metadata:
      name: descraibe-db-superuser-staging
      namespace: audiodeskription-staging
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: database
    type: kubernetes.io/basic-auth
