apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  # Kustomize adds the staging suffix, so the final SealedSecret and Secret
  # name is oidc-secret-staging in namespace audiodeskription-staging.
  name: oidc-secret
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: credentials
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgB/FDKaftOspzMqqTERpguM3F2e2hKBOwY/5cj5Nm2lu5C2WSS3KmE8HJn/SALFxBg/+5zEvwIGmNMj5HtTV0azgPYPfImU4mQ4/nfOOayWIPWZx3Pz/QuC6MCJyggsUVQ7Mn+EsSL3rPF7M0Q/pIPcDDcVntwdJhn/7u3bW/0TYjZjXcAZ7pr7elASuYQ4STou+lEYA36v8WtH51026BWIaOBVnzNB6ig2cGoooD+Dgd8yrJPB9XZbSPu/GyGQORv3mThc9zyqyqiaWnC+6Rp7CbvDU3JK7lsiTNHuFID6raH32kI2lw6I5ecSopUuzH4fwUdh/iaprBFIsOS5Oiqim8NgYpXvXNaJPlV57nLENsSb77/Wju2vK4kzBt4zN5OJZOqNfSHZ9Y2hUs1JbQmnYsv9Qz7HkLdrwvcVzsZJqY+cNW7fHmUarXP89G8EfpneJKVGXSc+Vwp8BC35LpRxxGo7vz6Hf8uJFGP1eG7MLbefEVgBaS9aKLEHFXpLPBVDG5ldUODspcWu33zbNimXuMyGrweY4QwWmcWJPcKUxXubgHz4gqxEixGmI4shcPZvrpL3tQCB1Jlb1jLWPp6DudYwHUf7q2ngOqRSK/rta2a914t+q1cqckWktpHOOWmUHufXvKYeEBGu6gNWus10cR/WJTG5NcRSsot1N8AEJ9dn62tlXDLuaDVTYRqvLfBph6zzUpFoyRON++fxdpAyVQqpvA9JlO66W0LJsvIVBQ==
    OIDC_SESSION_SECRET: AgBUCXt+GLMhcgSTanC1o3tovvS0wLQ3SRJfzPTYl10D2kW02KVC0Zm0Pt/w1yfS1rxX/LZa4AqouyBjC4VXy3fFJ8g5g/yCpyl19bFu6mMHixHOJV7IG8IRc83pzwOAJbIODTrcUQW72u9mQPLc92pcL2q00ExoxTOQmmYsl5fwGy0lXDLwDhFKHmBFTeYPor1+48cYNuUD4ooW1vZ5cyX902hWCs3Ww+5uDAjRLtPMRaWIudVxMVhSWplqdOkRx3sHJLlZVHrZpDWCjxYZwcF+eJ4lHtUBdSMBm0ejnSKZXXZlTens8CIVVTStLQ2w0EPw1AUEY7QPn3pB9wgWxgRuppRacsWoyTVmtMmeMMSa54UeWiqYuKB1i0hzWEAH6uIMKvQwn1NhRioc1c/WMDsY7ZbhVQctD1rJbAc6y6Phd1Rgb2Rzm5yYn7+Uy5/g044bpIan5pwwfoos58ykhbfJCFofUE3c7wS+Ce5n23iVzReGItpJL3nkUESjeZG83rjc31lf+3knsC71JGI/noIkczmAPPzz9blHFgGVyn9oxUSFGD8KDwOcVXStfc0bggcN6JMC93z/f1KLSkHXMVVYrse0U2jDgR98K8tk1w+7xUZ0GkNyRt3MV7WOEt9q/qnakFRzyahtjc+sAwq4YtJJidfgj3yVf1yjJm4d8loPRjda4cOWx80zao2jZWlmr4QE89ansnIcEz3fHCk88dGtJrZEdehwhULJstrwn1K8g1Zo286gHbWQ0+BpsGrAzSfDDxApT/zI6I+lc0YzZqg=
  template:
    metadata:
      name: oidc-secret-staging
      namespace: audiodeskription-staging
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: credentials
    type: Opaque
