apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  # Kustomize adds the staging suffix, so the final SealedSecret and Secret
  # name is openai-secret-staging in namespace audiodeskription-staging.
  name: openai-secret
  labels:
    app.kubernetes.io/name: audiodeskription
    app.kubernetes.io/component: credentials
spec:
  encryptedData:
    OPENAI_API_KEY: AgBirexXCFfLZFzyEgbxV9u4X1aAra1Iz7Iau6A2utTAxAStQA/wLvX/SiDgrVvJt31/K9ObXP2raeVfCCRI8ftxv03oFu+txoehRR8qtKqDQy+d4enyyCZai9sNJSazfnH5UuLvYAfzJxHjlMxA2Dnl2oTgMpcI1haM4c8l/KcI9AcQ76aANgJWrXRV8UUR+Fu+hK8vTtFfAs/oe0on9f73LL02DvDBrpoNrw2XdGNNsQXzupzAFCDZb3502jGfJYwjjsvbdbwdd8dcZky3jvdBEmeu3FzqtiTyuc5Jd/vHd7HrOagFYsdxL55XLTRg4Wb+FiBARy3TfvboIIw6xx/yFF2KmnoDicvo9yxlvvjpztJk44lE7v/poM6nCbKohm7ASjW/FXrvRQu4IcIGmYQYyRSpfROS/R0B4WAZPGTG5S+xdJwyXlJKmJwZPZJ07uSaygC6IcmxXnoITM7rFt+qaNQzijW0/bDRhdmcobITg0VIwfAdOJ5cBNfJSLJI3tJ4pfq6vCuWRL9csN8OoFtk/DVFbqOlChyfZAm+KFv0RrXFvwt/bRZaPSiJAUJTcjyRjck2dY3UX66vXgCYlRK12pAiqk7kJFI7yOnugQ8MrtpRBwuId3d+9UkDPDXzqqasGEq7tTN/kAYAMVRgwZBwXhw/c+IxVjAt3OpMxdN3yCsa+XfklCUzlrr71cmIKHQALE01Zxi2Qwb2rNVIamSJGbHnBfvcO832
    OPENAI_BASE_URL: AgCQtVIqPXocmtihkROBh5NDwSc/R73C+6VFy04xu5EM1jAv5bvsb9nurSLdgvrmze/OfvpNlxdHfsC0DHG1Prk79j7nNXBv8RevmFWDwniTJTOqReqFVvcSZQPRvDM3yA0PJoX86nGjQSC79UeHq8ZuOOty/gzbGFyTseJZbloJj42/FPsyc7F09OTOeAoS5ot8kqEpj6jL8zKDZutXKXF66/PbtP6fHxHiFL5Ilj8eDga/bY/whaKOH5xZrHauZx0ppQkld3T7gMpJAdbo/JRcCFzAiXH4VY0lXCyrhhvCGsK6HbzjiZafdandqY2k9R6poFmF/G9qK9jTeJ/rsrAdqKy4t+mzG0soaZrO76NpXJL4EAFLgrW4v3UAaxz+cf2IJXdtobxKsiragxBTPVZ8XjqZlk1P54o9kd9qA+RYhSZaOVYQlWiD/7q0/V7ZP0Pq0Z+tTe4WoFc9C+9LwHnNk2cunzB99fkgREehFeWg1rO53B72UZLi72Q3GLvWjizZdjgDYzAV3ouyQ3Yq+3BU7ER7w/5y38You30Wl9VpwhJIsRidDeVxE8ejDEHFELkpf7aFFlSyUbc8F/iCgcbQ6O7pkiMmh4Ph5Crwf9P0Yl0sSR9ewfSnJslvBlMjbvmvRejn+RMlSLTuABUeUNZydS9hPLt47XvQo67+l3rMtKEW/b5ev8z/skc2ml0hOnQZuxIphcMqaJLtygfHhyBgTjmBNMAfaFstOko=
  template:
    metadata:
      name: openai-secret-staging
      namespace: audiodeskription-staging
      labels:
        app.kubernetes.io/name: audiodeskription
        app.kubernetes.io/component: credentials
    type: Opaque
